# Generated by Django 5.1 on 2024-12-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0002_rename_direccion_venta_total_alter_venta_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='precio',
            new_name='id_empleado',
        ),
    ]
